In [39]:
import numpy as np
import itertools as it

In [76]:
def dist(couple):
    x = np.array(couple)
    print(x)
    return np.linalg.norm(x[0]-x[1])
    
    

In [85]:
odds = list()
evens = list()
x = it.product([0,1], repeat = 4)
for i in x:
    cup = np.array(i)
    if(sum(cup) % 2):
        odds.append(i)
    else:
        evens.append(i)
x = it.product(odds, evens)

mat = list()

for couple in x:
    mat.append(dist(couple))
    

[[0 0 0 1]
 [0 0 0 0]]
[[0 0 0 1]
 [0 0 1 1]]
[[0 0 0 1]
 [0 1 0 1]]
[[0 0 0 1]
 [0 1 1 0]]
[[0 0 0 1]
 [1 0 0 1]]
[[0 0 0 1]
 [1 0 1 0]]
[[0 0 0 1]
 [1 1 0 0]]
[[0 0 0 1]
 [1 1 1 1]]
[[0 0 1 0]
 [0 0 0 0]]
[[0 0 1 0]
 [0 0 1 1]]
[[0 0 1 0]
 [0 1 0 1]]
[[0 0 1 0]
 [0 1 1 0]]
[[0 0 1 0]
 [1 0 0 1]]
[[0 0 1 0]
 [1 0 1 0]]
[[0 0 1 0]
 [1 1 0 0]]
[[0 0 1 0]
 [1 1 1 1]]
[[0 1 0 0]
 [0 0 0 0]]
[[0 1 0 0]
 [0 0 1 1]]
[[0 1 0 0]
 [0 1 0 1]]
[[0 1 0 0]
 [0 1 1 0]]
[[0 1 0 0]
 [1 0 0 1]]
[[0 1 0 0]
 [1 0 1 0]]
[[0 1 0 0]
 [1 1 0 0]]
[[0 1 0 0]
 [1 1 1 1]]
[[0 1 1 1]
 [0 0 0 0]]
[[0 1 1 1]
 [0 0 1 1]]
[[0 1 1 1]
 [0 1 0 1]]
[[0 1 1 1]
 [0 1 1 0]]
[[0 1 1 1]
 [1 0 0 1]]
[[0 1 1 1]
 [1 0 1 0]]
[[0 1 1 1]
 [1 1 0 0]]
[[0 1 1 1]
 [1 1 1 1]]
[[1 0 0 0]
 [0 0 0 0]]
[[1 0 0 0]
 [0 0 1 1]]
[[1 0 0 0]
 [0 1 0 1]]
[[1 0 0 0]
 [0 1 1 0]]
[[1 0 0 0]
 [1 0 0 1]]
[[1 0 0 0]
 [1 0 1 0]]
[[1 0 0 0]
 [1 1 0 0]]
[[1 0 0 0]
 [1 1 1 1]]
[[1 0 1 1]
 [0 0 0 0]]
[[1 0 1 1]
 [0 0 1 1]]
[[1 0 1 1]
 [0 1 0 1]]
[[1 0 1 1]


In [89]:
mat = np.array(mat)
mat = mat.reshape((8,8))
mat = mat == 1

In [87]:
print(mat)

[[ True  True  True False  True False False False]
 [ True  True False  True False  True False False]
 [ True False  True  True False False  True False]
 [False  True  True  True False False False  True]
 [ True False False False  True  True  True False]
 [False  True False False  True  True False  True]
 [False False  True False  True False  True  True]
 [False False False  True False  True  True  True]]
